services:
  - type: web
    name: school-agent
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SERPER_API_KEY
        scope: project
      - key: GEMINI_API_KEY
        scope: project
